#!/usr/bin/env python
"""Single source of truth for the counts the docs quote — tools, calc ops, DocSpecs, packs (Phase J JD2).

The test count has its own script (scripts/sync_test_count.py, which stays the entrypoint for it); this one
covers every OTHER number a reader is told: the MCP tool count, the calc op count, the DocSpec kinds, the federal
pack total and its per-year split, the state and hand-fill pack counts. They drifted exactly as the test count
did — the core package's pyproject description still said "21 calculation ops" at 40, and the server's "22
tools" at 23 — so they are derived, never typed.

It also generates the form-by-year tables in docs/COVERAGE.md (between the GENERATED markers) from the packs
themselves, so the page a reader checks for "can it fill my form?" cannot drift either.

    python scripts/sync_doc_counts.py            # report the counts
    python scripts/sync_doc_counts.py --write    # rewrite every anchor and the coverage tables
    python scripts/sync_doc_counts.py --check    # nonzero exit if any anchor or table disagrees (CI)
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(REPO / "packages" / "core" / "src"), str(REPO / "packages" / "mcp-server" / "src")]

COVERAGE = REPO / "docs" / "COVERAGE.md"
GEN_BEGIN = "<!-- BEGIN GENERATED by scripts/sync_doc_counts.py --write — do not edit by hand -->"
GEN_END = "<!-- END GENERATED -->"
STATE_NAMES = {
    "al": "Alabama", "ak": "Alaska", "az": "Arizona", "ar": "Arkansas", "ca": "California", "co": "Colorado",
    "ct": "Connecticut", "de": "Delaware", "dc": "District of Columbia", "fl": "Florida", "ga": "Georgia",
    "hi": "Hawaii", "id": "Idaho", "il": "Illinois", "in": "Indiana", "ia": "Iowa", "ks": "Kansas",
    "ky": "Kentucky", "la": "Louisiana", "me": "Maine", "md": "Maryland", "ma": "Massachusetts", "mi": "Michigan",
    "mn": "Minnesota", "ms": "Mississippi", "mo": "Missouri", "mt": "Montana", "ne": "Nebraska", "nv": "Nevada",
    "nh": "New Hampshire", "nj": "New Jersey", "nm": "New Mexico", "ny": "New York", "nc": "North Carolina",
    "nd": "North Dakota", "oh": "Ohio", "ok": "Oklahoma", "or": "Oregon", "pa": "Pennsylvania",
    "ri": "Rhode Island", "sc": "South Carolina", "sd": "South Dakota", "tn": "Tennessee", "tx": "Texas",
    "ut": "Utah", "vt": "Vermont", "va": "Virginia", "wa": "Washington", "wv": "West Virginia",
    "wi": "Wisconsin", "wy": "Wyoming",
}


def counts() -> dict[str, object]:
    import anyio

    from taxfill_core.extract import DOC_SPECS
    from taxfill_mcp.server import mcp

    server = (REPO / "packages" / "mcp-server" / "src" / "taxfill_mcp" / "server.py").read_text(encoding="utf-8")
    federal: dict[int, int] = {}
    for pack in (REPO / "formpacks" / "federal").glob("*/*/pack.yaml"):
        year = int(pack.parent.parent.name)
        federal[year] = federal.get(year, 0) + 1
    return {
        "tools": len(anyio.run(mcp.list_tools)),
        "ops": len(set(re.findall(r'if op == "([a-z0-9_]+)"', server))),
        "doc_kinds": len(DOC_SPECS),
        "federal": sum(federal.values()),
        "federal_by_year": dict(sorted(federal.items())),
        "state": len(list((REPO / "formpacks" / "states").glob("*/*/*/pack.yaml"))),
        "state_by_year": {y: len(list((REPO / "formpacks" / "states").glob(f"*/{y}/*/pack.yaml")))
                          for y in sorted({int(p.parent.parent.name)
                                           for p in (REPO / "formpacks" / "states").glob("*/*/*/pack.yaml")})},
        "handfill": len(list((REPO / "formpacks").glob("**/handfill.yaml"))),
        "handfill_state": len(list((REPO / "formpacks" / "states").glob("**/handfill.yaml"))),
        "federal_form_years": {key: sorted(int(p.parent.parent.name)
                                           for p in (REPO / "formpacks" / "federal").glob(f"*/{key}/pack.yaml"))
                               for key in ("f1040", "f1040nr", "f8843")},
        **_state_years(),
        **_knowledge_years(),
    }


def _knowledge_years() -> dict[str, object]:
    """The knowledge years and planning year the README's coverage table quotes."""
    from taxfill_core.knowledge import provisional_marker

    know = REPO / "knowledge"
    federal = sorted(int(p.stem) for p in (know / "federal").glob("[0-9][0-9][0-9][0-9].yaml"))
    state_years = sorted({int(p.stem) for p in (know / "states").glob("*/[0-9][0-9][0-9][0-9].yaml")})
    return {"federal_knowledge": federal,
            "planning": [y for y in federal if provisional_marker("federal", y) is not None],
            "state_knowledge": state_years,
            "state_knowledge_counts": {y: len(list((know / "states").glob(f"*/{y}.yaml"))) for y in state_years}}


def _join(items: list) -> str:
    """'2023', '2023 and 2024', '2023, 2024 and 2025'."""
    items = [str(i) for i in items]
    return " and ".join(items) if len(items) <= 2 else f"{', '.join(items[:-1])} and {items[-1]}"


def _planning_note(planning: list[int]) -> str:
    return f"{_join(planning)} {'is' if len(planning) == 1 else 'are'} planning-only"


def _state_years() -> dict[str, object]:
    """Which jurisdictions can fill which post-2023 years — the state lists the docs quote (Phase J JS3b)."""
    states = REPO / "formpacks" / "states"
    years: dict[str, set[int]] = {}
    for pack in states.glob("*/*/*/*.yaml"):
        if pack.name in ("pack.yaml", "handfill.yaml") and pack.parent.parent.name.isdigit():
            years.setdefault(pack.parts[-4], set()).add(int(pack.parent.parent.name))
    post = {st: ys for st, ys in years.items() if any(y > 2023 for y in ys)}
    both = sorted(st.upper() for st, ys in post.items() if {2024, 2025} <= ys)
    only24 = sorted(st.upper() for st, ys in post.items() if 2024 in ys and 2025 not in ys)
    by_year = {y: sum(1 for ys in years.values() if y in ys) for y in sorted({y for ys in years.values() for y in ys})}
    fill_by_year = {y: sorted(st.upper() for st, ys in years.items() if y in ys) for y in by_year}
    return {"jurisdictions": len(years), "post2023": len(post), "both_years": both, "only_2024": only24,
            "juris_by_year": by_year, "fill_by_year": fill_by_year}


def _form_label(form: object) -> str:
    """A pack's ``form`` as a reader names it: '1040 Schedule 1' -> 'Schedule 1 (Form 1040)', '540' -> 'Form 540'."""
    text = str(form).strip()
    m = re.fullmatch(r"1040 Schedule (\S+)", text)
    if m:
        return f"Schedule {m.group(1)} (Form 1040)"
    return f"Form {text}" if text[:1].isdigit() or re.match(r"W-\d", text) else text


def _federal_group(key: str, handfill: bool) -> tuple[int, int, str]:
    """(table, order, key): the 1040 family, the 1040-NR family, payments/extensions/amendments, other forms
    by number, then reporting worksheets. A new ``sched_*`` key joins the 1040 schedules (``*_nr`` the 1040-NR
    family); any other new key lands among the other forms, by number."""
    nr_family = ["f1040nr", "sched_a_nr", "sched_nec", "sched_oi", "f8843"]
    if handfill:
        return (4, 0, key)
    if key == "f1040":
        return (0, 0, key)
    if key in nr_family or key.endswith("_nr"):
        return (1, nr_family.index(key) if key in nr_family else len(nr_family), key)
    m = re.fullmatch(r"sched_(\d+)([a-z]?)", key)
    if m:
        return (0, int(m.group(1)), key)
    if key.startswith("sched_"):
        return (0, 10**6, key)
    if key in ("f1040es", "f4868", "f1040x"):
        return (2, ["f1040es", "f4868", "f1040x"].index(key), key)
    digits = re.sub(r"\D", "", key)
    return (3, int(digits) if digits and not key.startswith("fw") else 10**6, key)


_FEDERAL_TABLES = ["Individual return — Form 1040 and its schedules", "Nonresident return — Form 1040-NR",
                   "Estimated tax, extensions and amended returns", "Other forms and attachments",
                   "Reporting worksheets (filed outside the return)"]


def _md_table(header: list[str], rows: list[list[str]]) -> list[str]:
    return ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|",
            *("| " + " | ".join(r) + " |" for r in rows)]


def coverage_markdown(c: dict) -> str:
    """The generated body of docs/COVERAGE.md: federal forms x years, jurisdictions x years, knowledge years."""
    from taxfill_core.discovery import load_form_pack
    from taxfill_core.filler import rehearsal_only
    from taxfill_core.knowledge import provisional_marker

    fed: dict[str, dict[int, str]] = {}
    labels: dict[str, tuple[int, str]] = {}
    groups: dict[str, tuple[int, int, str]] = {}
    for path in sorted((REPO / "formpacks" / "federal").glob("*/*/*.yaml")):
        if path.name not in ("pack.yaml", "handfill.yaml"):
            continue
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
        year, key, handfill = int(path.parent.parent.name), path.parent.name, path.name == "handfill.yaml"
        if handfill:
            cell = "worksheet"
        else:
            pack = load_form_pack(key, year, "federal")
            cell = "draft" if pack.source_status == "draft" else "rehearsal" if rehearsal_only(pack) else "✓"
        fed.setdefault(key, {})[year] = cell
        if year >= labels.get(key, (0, ""))[0]:
            labels[key] = (year, _form_label(data["form"]))
        groups[key] = _federal_group(key, handfill)
    planning = [y for y in sorted({y for ys in fed.values() for y in ys}) if provisional_marker("federal", y)]

    out = ["## Federal forms", ""]
    for index, title in enumerate(_FEDERAL_TABLES):
        keys = sorted((k for k in fed if groups[k][0] == index), key=lambda k: groups[k])
        if not keys:
            continue
        years = sorted({y for k in keys for y in fed[k]})
        head = ["Form", *(f"{y} †" if y in planning else str(y) for y in years)]
        out += [f"### {title}", "", *_md_table(head, [[labels[k][1], *(fed[k].get(y, "—") for y in years)]
                                                       for k in keys]), ""]
        if index == 0 and "f1040" in fed:
            orphan = sorted({y for k in keys for y in fed[k]} - set(fed["f1040"]))
            if orphan:
                out += [f"The {_join(orphan)} schedule packs serve Form 1040-NR, which attaches them; there is no "
                        f"Form 1040 pack for {_join(orphan)}.", ""]
    worksheets = sum(1 for k in fed for cell in fed[k].values() if cell == "worksheet")
    out += [f"**{c['federal']} federal form packs** plus {worksheets} reporting worksheets.", "",
            "✓ = fills the final IRS form · draft = mapped from the IRS early-release draft; fills in rehearsal mode "
            "only, until the final form posts · rehearsal = a final revision used in a planning year; rehearsal mode "
            "only · worksheet = values to key into another filing system"
            + (f" · † = planning year ({', '.join(map(str, planning))}): for projections and dress rehearsals — its "
               "return is filed after the year ends" if planning else "") + ".", ""]

    states = REPO / "formpacks" / "states"
    cells: dict[str, dict[int, list[str]]] = {}
    for path in sorted(states.glob("*/*/*/*.yaml")):
        if path.name not in ("pack.yaml", "handfill.yaml") or not path.parent.parent.name.isdigit():
            continue
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
        st, year = path.parts[-4], int(path.parent.parent.name)
        label = _form_label(data["form"])
        if path.name == "handfill.yaml":
            label += " ✎"
        else:
            pack = load_form_pack(path.parent.name, year, f"states/{st}")
            label += " (draft)" if pack.source_status == "draft" else " (rehearsal)" if rehearsal_only(pack) else ""
        cells.setdefault(st, {}).setdefault(year, []).append(label)
    years = sorted({y for ys in cells.values() for y in ys})
    rows = [[f"{st.upper()} — {STATE_NAMES.get(st, st.upper())}",
             *(", ".join(sorted(cells[st].get(y, []))) or "—" for y in years)] for st in sorted(cells)]
    per_year = ", ".join(f"{sum(1 for st in cells if y in cells[st])} in {y}" for y in years)
    out += ["## State forms", "",
            f"State returns for **{len(cells)} income-tax jurisdictions** — {per_year} — from "
            f"**{c['state']} fillable state packs** and "
            f"**{c['handfill'] - worksheets} print-and-hand-fill worksheets**. Each row lists the resident return and, "
            "where mapped, the state's separate nonresident / part-year return (such as CA Form 540NR or NY IT-203).",
            "",
            *_md_table(["Jurisdiction", *map(str, years)], rows), "",
            "✎ = print-and-hand-fill: that year's official form is not a fillable PDF, so `hand_fill_worksheet` "
            "lists every line and `fill_form` stamps the values onto the official blank. "
            "(draft) / (rehearsal) = fills in rehearsal mode only, as in the federal legend. "
            "— = not yet mapped for that year (the tax itself can still be *computed* from the state knowledge "
            "pack).", ""]

    no_tax = yaml.safe_load((REPO / "knowledge" / "states" / "no_income_tax.yaml").read_text(encoding="utf-8"))
    none = ", ".join(sorted(e["state"] for e in no_tax["none"]))
    partial = " and ".join(sorted(e["state"] for e in no_tax["wages_only_exempt"]))
    fed_years, know_planning = c["federal_knowledge"], c["planning"]
    counts = c["state_knowledge_counts"]
    complete = [y for y, n in counts.items() if n == c["jurisdictions"]]
    partly = [f"{n} in {y}" for y, n in counts.items() if n != c["jurisdictions"]]
    per_state_year = (f"all {c['jurisdictions']} income-tax jurisdictions for {_join(complete)}" if complete else "")
    if partly:
        per_state_year += ("; " if per_state_year else "income-tax jurisdictions ") + ", ".join(partly)
    out += ["## Tax knowledge (rates, thresholds, credits, addresses)", "",
            f"- **Federal:** {fed_years[0]}–{fed_years[-1]}"
            + (f" ({_planning_note(know_planning)}: projections, not filing)" if know_planning else "") + ".",
            f"- **States:** {per_state_year}. No return is needed for wages in {none}; {partial} tax some investment "
            "income in some years (see `knowledge/states/no_income_tax.yaml`), which `state_scope` flags.",
            ""]
    return "\n".join(out).rstrip("\n")


def anchors(c: dict) -> list[tuple[Path, str, str]]:
    """(file, regex, replacement) for every place a count is quoted. Each regex must match exactly once."""
    readme, skill = REPO / "README.md", REPO / "skills" / "claude" / "SKILL.md"
    tools_md = REPO / "docs" / "TOOLS.md"
    roadmap = REPO / "docs" / "dev" / "ROADMAP.md"
    sy, jy = c["state_by_year"], c["juris_by_year"]
    know, planning, ffy = c["federal_knowledge"], c["planning"], c["federal_form_years"]
    filing_1040 = [y for y in ffy["f1040"] if y not in planning]
    state_complete = [y for y, n in c["state_knowledge_counts"].items() if n == c["jurisdictions"]]
    roster = " and ".join(f"TY{y} for **{len(c['fill_by_year'][y])}** ({', '.join(c['fill_by_year'][y])})"
                          for y in (2024, 2025))
    return [
        (readme, r"\| \*\*Federal forms\*\* \| Form 1040 with its schedules and attachments for TY\d{4}–\d{4}, Form 1040-NR "
                 r"from TY\d{4}, Form 8843 from TY\d{4} — \d+ packs(?:, including TY\d{4} planning drafts)?",
         f"| **Federal forms** | Form 1040 with its schedules and attachments for TY{filing_1040[0]}–{filing_1040[-1]}, "
         f"Form 1040-NR from TY{ffy['f1040nr'][0]}, Form 8843 from TY{ffy['f8843'][0]} — {c['federal']} packs"
         + (f", including TY{planning[-1]} planning drafts" if planning else "")),
        (readme, r"\| \*\*Federal tax law\*\* \| \d{4}–\d{4}(?: \((?:\d{4}(?:, | and ))*\d{4} (?:is|are) planning-only\))?",
         f"| **Federal tax law** | {know[0]}–{know[-1]}" + (f" ({_planning_note(planning)})" if planning else "")),
        (readme, r"\| \*\*State forms\*\* \| Resident returns for \d+ of the \d+ income-tax jurisdictions in TY2025, \d+ in "
                 r"TY2024, (?:all )?\d+ in TY2023",
         f"| **State forms** | Resident returns for {jy[2025]} of the {c['jurisdictions']} income-tax jurisdictions in "
         f"TY2025, {jy[2024]} in TY2024, {'all ' if jy[2023] == c['jurisdictions'] else ''}{jy[2023]} in TY2023"),
        (readme, r"\| \*\*Print-and-hand-fill\*\* \| \d+ state-return worksheets",
         f"| **Print-and-hand-fill** | {c['handfill_state']} state-return worksheets"),
        (readme, r"\| \*\*State tax law\*\* \| All 50 states \+ DC, \d{4}–\d{4}(?: \(\d{4}: \d+ jurisdictions? so far\))*",
         f"| **State tax law** | All 50 states + DC, {state_complete[0]}–{state_complete[-1]}"
         + "".join(f" ({y}: {n} jurisdiction{'s' if n != 1 else ''} so far)"
                   for y, n in c["state_knowledge_counts"].items() if y not in state_complete)),
        (readme, r"\| \*\*Documents read\*\* \| \d+ tax-document kinds", f"| **Documents read** | {c['doc_kinds']} tax-document kinds"),
        (readme, r"Look up the \d+ MCP tools, the \d+ calc ops", f"Look up the {c['tools']} MCP tools, the {c['ops']} calc ops"),
        (tools_md, r"All \d+ tools are available today", f"All {c['tools']} tools are available today"),
        (tools_md, r"registers exactly \d+", f"registers exactly {c['tools']}"),
        (tools_md, r"Deterministic tax math — \d+ ops \(`calc\(op, args\)`\)",
         f"Deterministic tax math — {c['ops']} ops (`calc(op, args)`)"),
        (skill, r"deterministic tax math — \d+ ops, one bullet each", f"deterministic tax math — {c['ops']} ops, one bullet each"),
        (skill, r"The federal set is \*\*\d+ packs\*\*", f"The federal set is **{c['federal']} packs**"),
        (REPO / "docs" / "dev" / "DEV_PLAN.md", r"It carries \d+ kinds", f"It carries {c['doc_kinds']} kinds"),
        (REPO / "packages" / "mcp-server" / "README.md", r"## Tools \(dev plan §8\) — all \d+",
         f"## Tools (dev plan §8) — all {c['tools']}"),
        (REPO / "packages" / "mcp-server" / "README.md", r"`calc` \(\d+\ndeterministic ops",
         f"`calc` ({c['ops']}\ndeterministic ops"),
        (REPO / "docs" / "dev" / "PUBLISHING.md", r"assert len\(asyncio\.run\(s\.mcp\.list_tools\(\)\)\) == \d+",
         f"assert len(asyncio.run(s.mcp.list_tools())) == {c['tools']}"),
        (REPO / "docs" / "dev" / "PUBLISHING.md", r"It declares the \*\*\d+ tools\*\*", f"It declares the **{c['tools']} tools**"),
        (REPO / "packages" / "core" / "pyproject.toml", r"and \d+ calculation ops", f"and {c['ops']} calculation ops"),
        (REPO / "packages" / "mcp-server" / "pyproject.toml", r"cited tax math \(\d+ tools\)",
         f"cited tax math ({c['tools']} tools)"),
        # Phase J JS3b: the state form-pack counts (they drifted: "61 state" survived the UT 2025 port).
        (skill, r"are \*\*thinner and uneven\*\*: \d+ packs", f"are **thinner and uneven**: {c['state']} packs"),
        # Phase J JS5 / the 2026-10 cleanup: the per-year state form roster every skill file quotes (the old
        # sentence named only "2024 and 2025" and "2024 only" states, so the 2025-only ports went unlisted)
        *[(path, r"TY2024 for \*\*\d+\*\* \([A-Z, ]+\) and TY2025 for \*\*\d+\*\* \([A-Z, ]+\)", roster)
          for path in (skill, REPO / "skills" / "codex" / "AGENTS.md", REPO / "skills" / "copilot" / "instructions.md")],
        (roadmap, r"\*\*State form packs — \d+ across three years\*\* \(TY2023 \d+ / TY2024 \d+ / TY2025 \d+\)",
         f"**State form packs — {c['state']} across three years** (TY2023 {sy[2023]} / TY2024 {sy[2024]} / "
         f"TY2025 {sy[2025]})"),
        (roadmap, r"\*\*\d+ of the 42 jurisdictions fill a post-2023 year\*\*",
         f"**{c['post2023']} of the 42 jurisdictions fill a post-2023 year**"),
        # the per-year roster (the old "both years / 2024 only" split had no slot for the 2025-only ports)
        (roadmap, r"fill a post-2023 year\*\* —\n> TY2024 for \*\*\d+\*\* \([A-Z, ]+\) and TY2025 for \*\*\d+\*\* \([A-Z, ]+\) — after",
         f"fill a post-2023 year** —\n> {roster} — after"),
        (roadmap, r"For the remaining \*\*\d+\*\*, state \*knowledge\*",
         f"For the remaining **{c['jurisdictions'] - c['post2023']}**, state *knowledge*"),
        (roadmap, r"That asymmetry is now \d+\n> jurisdictions wide",
         f"That asymmetry is now {c['jurisdictions'] - c['post2023']}\n> jurisdictions wide"),
        (roadmap, r"\*\*\d+ of the 42 jurisdictions\*\* can fill a post-2023 year —\n      TY2024 for \*\*\d+\*\* \([A-Z, ]+\) and "
                  r"TY2025 for \*\*\d+\*\* \([A-Z, ]+\)\. For the\n      other \*\*\d+\*\*",
         f"**{c['post2023']} of the 42 jurisdictions** can fill a post-2023 year —\n      {roster}. For the\n      "
         f"other **{c['jurisdictions'] - c['post2023']}**"),
        (roadmap, r"\*\*\d+ form packs total\*\* — \d+ `pack\.yaml` \(\d+ federal \+ \d+ state\) \+ \d+",
         f"**{c['federal'] + c['state'] + c['handfill']} form packs total** — {c['federal'] + c['state']} `pack.yaml` "
         f"({c['federal']} federal + {c['state']} state) + {c['handfill']}"),
        (roadmap, r"The state \d+ breaks down \*\*TY2023 \d+ / TY2024 \d+ / TY2025 \d+\*\*",
         f"The state {c['state']} breaks down **TY2023 {sy[2023]} / TY2024 {sy[2024]} / TY2025 {sy[2025]}**"),
        (roadmap, r"38 via fillable AcroForm \(\d+ packs across TY2023–TY2025\)",
         f"38 via fillable AcroForm ({c['state']} packs across TY2023–TY2025)"),
        (roadmap, r"TY2023-only\*\*: \d+ packs across TY2023 \(\d+\) / TY2024 \(\d+\) / TY2025 \(\d+\)",
         f"TY2023-only**: {c['state']} packs across TY2023 ({sy[2023]}) / TY2024 ({sy[2024]}) / TY2025 ({sy[2025]})"),
    ]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    c = counts()
    print(f"tools={c['tools']} ops={c['ops']} doc_kinds={c['doc_kinds']} federal={c['federal']} "
          f"({', '.join(f'{y}:{n}' for y, n in c['federal_by_year'].items())}) state={c['state']} "
          f"handfill={c['handfill']}")
    stale, texts = [], {}
    for path, pattern, replacement in anchors(c):
        text = texts.setdefault(path, path.read_text(encoding="utf-8"))
        hits = re.findall(pattern, text)
        if len(hits) != 1:
            print(f"ANCHOR LOST: {path.relative_to(REPO)} has {len(hits)} match(es) for {pattern!r} — fix the "
                  f"anchor or this script", file=sys.stderr)
            return 2
        if hits[0] != replacement:
            stale.append(f"{path.relative_to(REPO)}: {hits[0]!r} -> {replacement!r}")
            texts[path] = re.sub(pattern, lambda _m: replacement, text, count=1)
    text = texts.setdefault(COVERAGE, COVERAGE.read_text(encoding="utf-8"))
    if text.count(GEN_BEGIN) != 1 or text.count(GEN_END) != 1:
        print(f"ANCHOR LOST: {COVERAGE.relative_to(REPO)} needs exactly one {GEN_BEGIN!r} ... {GEN_END!r} block",
              file=sys.stderr)
        return 2
    start, end = text.index(GEN_BEGIN), text.index(GEN_END) + len(GEN_END)
    block = f"{GEN_BEGIN}\n\n{coverage_markdown(c)}\n\n{GEN_END}"
    if text[start:end] != block:
        stale.append(f"{COVERAGE.relative_to(REPO)}: the generated coverage tables differ from the packs")
        texts[COVERAGE] = text[:start] + block + text[end:]
    for line in stale:
        print(("updated " if args.write else "STALE ") + line)
    if args.write:
        for path, text in texts.items():
            if text != path.read_text(encoding="utf-8"):
                path.write_text(text, encoding="utf-8")
        return 0
    if args.check and stale:
        print(f"{len(stale)} stale count(s) — run: uv run python scripts/sync_doc_counts.py --write", file=sys.stderr)
        return 1
    if not stale:
        print("every quoted count is current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
